# profiles.yml

retail:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/serviceaccount.json
    project: onlineretail-413310
    dataset: retail
    threads: 1
    timeout_seconds: 300
    location: US